server:
  port: 8080
  servlet:
    encoding:
      charset: utf-8

spring:
  messages:
    basename: META-INF/local/messages
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.106.115.32:3306/wht_dev?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: root
    password: Root@nong123
  redis:
    # Redis数据库索引（默认为0）
    database: 2
    # Redis服务器地址
    host: 47.106.115.32
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: nong135790
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 1
    # 连接超时时间（毫秒）
    timeout: 5000